// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package privacy_sandbox.server_common.telemetry;

message TelemetryConfig {
  enum TelemetryMode {
    UNKNOWN_TYPE = 0;

    // No telemetry (metrics/traces).
    OFF = 1;

    // Production mode.
    // `Privacy::kImpacting` metrics must be noised.
    PROD = 2;

    // Same as PROD in prod build;
    // In experiment build, enables metrics without noise; and tracing is also
    // enabled.
    EXPERIMENT = 3;

    // Same as PROD in prod build;
    // In experiment build, exports both noised and raw data for
    // `Privacy::kImpacting` metrics.
    COMPARE = 4;
  }
  TelemetryMode mode = 1;

  // If non-empty, only output these metrics in both here and default list.
  // If empty, the default list of metrics is used.
  repeated MetricConfig metric = 2;

  // The time interval between two consecutive metric exports.
  int32 metric_export_interval_ms = 3;

  // The time interval between two consecutive differential privacy aggregated.
  // metric exports, must be at least metric_export_interval_ms
  int32 dp_export_interval_ms = 4;

  repeated MetricConfig custom_udf_metric = 5;

}

message MetricConfig {
  // name should match `metrics::Definition` in the list of server's metric
  // provided when creating `ContextMap`
  optional string name = 1;

  // overwrite the public_partitions_ in metric definition if not empty
  repeated string public_partitions = 2;

  // overwrite the max_partitions_contributed_ in metric definition if being set
  optional int32 max_partitions_contributed = 3;

  // overwrite the lower_bound_ in metric definition if being set
  optional double lower_bound = 4;

  // overwrite the upper_bound_ in metric definition if being set
  optional double upper_bound = 5;

  // overwrite the privacy_budget_weight_ in metric definition if being set
  optional double privacy_budget_weight = 6;

  // overwrite the drop_noisy_values_probability_ in metric definition if being set
  optional double drop_noisy_values_probability = 7;

  //overwrite metric description
  optional string description = 8;

  //overwrite partition_type in metric definition if being set.
  //Only used by custom_udf_metric.
  optional string partition_type = 9;

}

message GoogleTelemetryConfig {
  // Default false. Set to true to stop sharing all telemetry with Google.
  bool disable = 1;

  /*
   * Metric Selection Logic:
   *
   * There exists a pre-selected list of metrics that are shared with Google. Below are some options that one can set to
   * customize what is shared.
   *
   * The selection process follows a specific order of precedence:
   *
   * 1. disable (Highest Precedence):
   *    - If 'disable' is true, no metrics are shared, including the preselected list.
   *
   * 2. override_metrics:
   *    - If 'override_metrics' is set (non-empty), it completely overrides the 'additional_metrics' and 'omitted_metrics' fields.
   *    - Only metrics explicitly listed in 'override_metrics' will be shared.
   *
   * 3. additional_metrics and omitted_metrics (only considered if 'disable' is false and 'override_metrics' is empty):
   *    - Start with a pre-defined (default) list of metrics.
   *    - Add metrics specified in 'additional_metrics' to the default list.
   *    - Remove metrics specified in 'omitted_metrics' from the combined list.
   *    - If a metric is present in both 'additional_metrics' and 'omitted_metrics', it will be omitted (omitted_metrics takes precedence).
   *
   * In essence:
   * - If 'disable' is true: No metrics are shared.
   * - Else if 'override_metrics' is set: Only metrics in 'override_metrics' are shared.
   * - Else: Start with a default list, add 'additional_metrics', then remove 'omitted_metrics'.
   *
   * This config supports regex full match. For example, if the pattern is "metric.*", then metrics with name such as
   * "metric_one", "metric.one", "metricOne" will be shared.
   */

  // Default empty.
  // If specified, ONLY metrics specified in this list will be shared with Google. This will override metrics specified in omitted_metrics.
  repeated string override_metrics = 2;

  // Default empty.
  // If specified, additional metrics that are not part of the pre-defined list of metrics will be shared with Google.
  repeated string additional_metrics = 3;

  // Default empty.
  // If specified, metric names in this list will be omitted from sharing w/ Google.
  repeated string omitted_metrics = 4;
}
